version: "3.9"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0440

  node-app:
    image: feedbee/node-sample-app
    ports:
      - "3000:3000"
    environment:
      - PERSISTENT=true
    deploy:
      replicas: 2
    depends_on:
      - redis
  
  redis:
    image: redis:alpine

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

configs:
  nginx-config:
    file: ./nginx.conf
